"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
# 简化配置，不使用decouple
# try:
#     from decouple import config
# except ImportError:
#     from python_decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-in-production-12345'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['.vercel.app', '.now.sh', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = []

MIDDLEWARE = []

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database - 不需要数据库
DATABASES = {}

# 日志配置 - 简化
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# 会话配置 - 禁用
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_AGE = 1209600  # 14天


# Password validation - 禁用（不需要认证）
# AUTH_PASSWORD_VALIDATORS = []


# Internationalization - 简化
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = False  # 不需要国际化
USE_TZ = False    # 不需要时区


# Static files - 禁用（不需要）
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 静态文件查找器 - 禁用（不需要）
# STATICFILES_FINDERS = []

# Whitenoise配置 - 禁用（不需要）
# STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# Default primary key field type - 禁用（不需要）
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 禁用数据库相关功能
# DATABASE_ROUTERS = []

# 确保静态文件正常工作 - 禁用（不需要）
# STATICFILES_IGNORE_PATTERNS = []
# STATICFILES_USE_FINDERS = True

# 认证相关配置 - 禁用
# LOGIN_URL = '/admin/login/'
# LOGIN_REDIRECT_URL = '/admin/'

# 安全设置 - 静态网站最小化
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
